### ISSUE TITLE
Gray out update button again when case sensitive switch is restored to prevous state

### ISSUE THREAD

**Issue by Mister-Muffin** [Mr-Pine/Link-shortener-website#2]
:)

**Comment by Mr-Pine** [comment]
Pls screenshot. Not able to replicate 🙃

**Comment by Mister-Muffin** [comment]
SOOOOOOOOOOOOOOOO meine Damen und Herren

**Comment by Mister-Muffin** [comment]
![grafik](https://user-images.githubusercontent.com/45641704/147986506-52d5d48a-d292-48fe-96a2-460f9f847caf.png)
![grafik](https://user-images.githubusercontent.com/45641704/147986531-36b07550-c750-4d97-a187-eb1a49141a50.png)
![grafik](https://user-images.githubusercontent.com/45641704/147986542-b65bcea0-bba4-485d-a57f-0a41bbf00a94.png)

**Comment by Mr-Pine** [comment]
Ah le problem de le ende de back

**Comment by Mister-Muffin** [comment]
mais oui

**Comment by Mister-Muffin** [comment]
le problem fixed?

**Comment by Mr-Pine** [comment]
https://github.com/Mr-Pine/link-shortener-server

**Comment by Mr-Pine** [comment]
auchnoch: DB updaten

**Comment by Mister-Muffin** [comment]
brauch ich die API, damit sich das wieder ausgraut?

**Comment by Mr-Pine** [comment]
wahrscheinlich, weil das auch ein neues Feature ist. Bei mir funktioniert's also 🤷‍♂️
